pep/adminpanel/urls.py
from django.urls import path
from adminpanel.views import HomeView, AdminView, AdView, NormalView, MyUserView, MyStatusView, IndexView, ListBlog
from adminpanel import views


app_name = 'adminpanel'

urlpatterns = [
    path('home/', HomeView.as_view(), name="home"),
    path('index/', IndexView.as_view(), name="index"),
    path('getUser/', AdminView.as_view(), name="adminn"),
    path('getSuper/', AdView.as_view(), name="ad"),
    path('getNormal/', NormalView.as_view(), name="normaluser"),
    path('userstatus/', MyUserView.as_view(), name='userstatus'),
    path('status/<int:pk>', MyStatusView.as_view(), name='status'),
    path('lists/',views.ListBlog.as_view(),name='listblog'),
    path('unpublished/<int:pk>/', views.unpublished, name='unpublished'),
    path('published/<int:pk>/', views.published, name='published')
]
    

pep/blogapp/urls.py
from django.urls import path
from blogapp import views
from blogapp.views import Blogging, BlogCreate
from django.conf import settings
from django.conf.urls.static import static

app_name = "blogapp"

urlpatterns = [
    path('', views.Blogging.as_view(),name="index"),
    path('create/', views.BlogCreate.as_view(),name="create"),
    path('update/<int:pk>/',views.BlogUpdate.as_view(),name='update'),
    path('detail/<int:pk>/',views.BlogDetail.as_view(),name='detail'),
    path('delete/<int:pk>/',views.BlogDelete.as_view(),name='delete'),
    path('list/',views.BlogList.as_view(),name='list'),
    path('listHome/',views.BlogHome.as_view(),name='bloghome'),
    path('listRate/',views.BlogListRating.as_view(),name='blograte'),
    path('remove/<int:pk>/', views.remove, name='remove'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('results/', views.SearchView.as_view(), name='search'),
    path('like/<int:pk>/', views.postLike, name='like'),
    path('dislike/<int:pk>/', views.postDisLike, name='dislike'),
    path('list_user/',views.BlogListUser.as_view(),name='listuser'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pep/modules/product/ProductApp/urls.py
from django.urls import path
from modules.product.ProductApp import views

app_name = "ProductApp"

urlpatterns = [
    path('home/', views.Home, name='home'),
    path('create/', views.ProductCreate.as_view(), name="productcreate"),
    path('update/<int:pk>/', views.ProductUpdate.as_view(), name="productupdate"),
    path('detail/<int:pk>/', views.ProductDetail.as_view(), name="productdetail"),
    path('delete/<int:pk>/', views.ProductDelete.as_view(), name="productdelete"),
    path('list/', views.ProductList.as_view(), name="productlist"),
    path('order/<int:pk>', views.OrderCreate.as_view(), name="ordercreate"),
    path('order_done/', views.order_done, name="order_done"),
    path('orderlist/', views.OrderList.as_view(), name="orderlist"),
    path('orderdetail/<int:pk>/', views.OrderDetail.as_view(), name="orderdetail"),
    path('cartlist/', views.CartList.as_view(), name="cartlist"),
    path('addcart/<int:pk>', views.addcart, name="addcart"),
    path('removecart/<int:pk>', views.removecart, name="removecart"),
    path('ordercart/<int:pk>/', views.OrderCart.as_view(), name="ordercart"),
    path('updatecart/<int:pk>/', views.AddCartUpdate.as_view(), name="updatecart"),
    path('payment/<int:pk>/', views.PaymentOrder, name='payment'),
    path('paymentcart/<int:pk>/', views.PaymentCart, name='paymentcart'),
    path('paymentstatus/<int:pk>/', views.PaymentStatus, name = 'paymentstatus')
]

pep/mypep/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as pep_views
from mypep.views import MyView, SignUpView, UserLogin, ProfileUpdate, ProfileDetail, MyDetailView


app_name = "mypep"

urlpatterns = [
    path('', MyView.as_view(), name="base"),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='mypep:login'), name='logout'),

    path('update/<int:pk>', ProfileUpdate.as_view(), name='update'),

    path('detail/', MyDetailView.as_view(), name='detail'),


    path('change/', pep_views.PasswordChangeView.as_view(template_name="mypep/password_change_form.html",
                                                          success_url=reverse_lazy('mypep:password_change_done')), name='password_change'),
    path('change_done/', pep_views.PasswordChangeDoneView.as_view(template_name="mypep/password_change_done.html",),
                                                                  name='password_change_done'),

    path('reset_password/', pep_views.PasswordResetView.as_view(template_name="mypep/password_reset_form.html",success_url=reverse_lazy('mypep:password_reset_done')), 
    name = 'password_reset'),
    path('reset_password_sent/', pep_views.PasswordResetDoneView.as_view(template_name="mypep/password_reset_done.html"), 
    name = 'password_reset_done'),
    path('reset/<uidb64>/<token>', pep_views.PasswordResetConfirmView.as_view(template_name="mypep/password_reset_confirm.html",success_url=reverse_lazy('mypep:password_reset_complete')), 
    name = 'password_reset_confirm'),
    path('reset_password_complete/', pep_views.PasswordResetCompleteView.as_view(template_name="mypep/password_reset_complete.html"), 
    name = 'password_reset_complete')
]

pep/pep/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.templatetags.static import static
from django.conf.urls.static import static

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path("admin/", admin.site.urls),
    path("mypep/", include('mypep.urls')),
    path("adminpanel/", include('adminpanel.urls')),
    path("blogapp/", include('blogapp.urls')),
    path("blogcomment/", include('blogcomment.urls')),
    path("product/",include('modules.product.ProductApp.urls', namespace='product'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pep/adminpanel/models.py
from django.db import models

# Create your models here.

pep/adminpanel/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.views.generic.list import ListView
from blogapp.models import PostBlog
from blogapp.forms import BlogForm
from django.utils import timezone
import datetime


class HomeView(View):
    """
    Admin Panel page view
    """
    def get(self, request):
        """
        Function to render Admin panel page
        """
        if request.user.is_staff:
            return render(request, 'adminpanel/hello.html')
        else:
            return render(request, 'adminpanel/index.html')


class IndexView(View):
    """
    Home page view
    """
    def get(self, request):
        """
        Function to render home page
        """
        return render(request, 'adminpanel/index.html')


class ListBlog(ListView):
    """
    class for blog list to show
    """
    model = PostBlog
    form_class = BlogForm
    template_name = "adminpanel/bloglists.html"

    def get(self, request):
        """
        get function to resrict access to certain users
        """
        object_list = PostBlog.objects.all()
        if request.user.is_staff:
            return render(request, "adminpanel/bloglists.html", {'object_list':object_list})
        else:
            return render(request, 'adminpanel/index.html')

    def choices(self):
        """
        function to return only published blogs
        """
        return PostBlog.objects.filter(status=1)


def published(request, pk):
    """
    function to change status to published
    """
    blog = PostBlog.objects.get(id=pk)
    blog.status = 1
    date = timezone.now()
    blog.published_date = timezone.now()
    a = 1
    blog.save()
    return redirect('adminpanel:listblog')

def unpublished(request, pk):
    """
    function to change status to unpublished
    """
    blog = PostBlog.objects.get(id=pk)
    blog.status = 2
    blog.published_date = None
    blog.save()
    return redirect('adminpanel:listblog')

def publish_date(request, pk):
    blog = PostBlog.objects.get(id=pk)
    blog.published_date = timezone.now()
    blog.save()
    return redirect('adminpanel:listblog')


class AdminView(View):
    """
    Class which has a function which returns number of active users
    """
    def get(self, request):
        """
        Function which returns number of active users
        """
        usercount = User.objects.filter(is_active=True).count()
        return JsonResponse(usercount, safe=False)


class AdView(View):
    """
    Class which has a function which returns number of superuser users
    """
    def get(self, request):
        """
        Function which returns number of superuser users
        """
        superuser = User.objects.filter(is_superuser=True).count()
        return JsonResponse(superuser, safe=False)


class NormalView(View):
    """
    Class which has a function which returns number of normal users
    """
    def get(self, request):
        """
        Function which returns number of normal users
        """
        normaluser = User.objects.filter(is_superuser=False).count()
        return JsonResponse(normaluser, safe=False)


class MyUserView(View):
    """
    Class to restrict access to certain page for users
    """
    def get(self, request):
        """
        get Function to restrict access to certain page for users
        """
        users = User.objects.all()
        if self.request.user.is_superuser:
            return render(request, 'adminpanel/hey.html', {'users': users})
        else:
            return redirect("/")


class MyStatusView(View):
    """
    User Status view
    """
    def get(self, request, *args, **kwargs):
        """
        Function to render User Status page
        """
        users = User.objects.all()
        user_id = kwargs['pk']
        user = User.objects.get(pk=user_id)
        if request.user.is_superuser:
            if user.is_superuser:
                user.is_superuser=False
                user.save()
            else:
                user.is_superuser=True
                user.save()

        return render(request, 'adminpanel/hey.html', {'users': users})

pep/adminpanel/templates/adminpanel/admin.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}
        {% endblock %}</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    {% block style %}
        {% endblock %}

  </head>
  <body>
    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

pep/adminpanel/templates/adminpanel/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}
        {% endblock %}</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    {% block style %}
        {% endblock %}

  </head>
  <body>
    {% include 'adminpanel/header.html' %}
    {% block content %}
    {% endblock %}
    {% include 'adminpanel/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script type="text/javascript">
    <script src="https://use.fontawesome.com/fe459689b4.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

pep/adminpanel/templates/adminpanel/bloglists.html
{% extends 'adminpanel/admin.html' %}
{% load static %}
{% block content %}

<section >
    <div class="row">
        <div class = "col-sm-3">
            <h4 class="mt-5 mx-3">Interface</h4>
            <ul class="mt-4">
                
                <li class="my-3 mx-3">

                    <a class="text-dark text-decoration-none" href ="{% url 'adminpanel:home' %}">OverView</a>

                </li>
                <li class="my-3 mx-3">

                    <a class="text-dark text-decoration-none" href ="{% url 'adminpanel:userstatus' %}">User Status</a>

                </li>


                <li class="my-3 mx-3">
                    <a class="text-dark text-decoration-none fw-bold" id ="drop1" data-bs-toggle="collapse" href="#collapseExample1" role="button" aria-expanded="false" aria-controls="collapseExample1">
                        Blog List
                    </a>


                </li>


                <li class="my-3 mx-3">
                    <a class="text-dark text-decoration-none" id ="drop2" data-bs-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample2">
                        Pages
                    </a>


                </li>
            </ul>

            

            <h4 class="mt-5 mx-3">UI Toolkits</h4>
            <ul class="mt-4">
                <li class="my-3 mx-3">Components</li>
                <li class="my-3 mx-3">Content</li>
                <li class="my-3 mx-3">Forms</li>
                <li class="my-3 mx-3">Utilities</li>
            </ul>

            <h4 class="mt-5 mx-3">Plugins</h4>
            <ul class="mt-4">
                <li class="my-3 mx-3">Charts</li>
                <li class="my-3 mx-3">Code Blocks</li>
                <li class="my-3 mx-3">Data Tables</li>
                <li class="my-3 mx-3">Data Picker</li>
            </ul>

        </div>


        <div class = "col-md-9">
            <div class="row ">
                <div class = "col-sm-6 ">
                    <div class ="container-xl-p-5 ms-2">
                        <h2 class ="display-6 fw-bold mb-0 mt-5">Dashboard</h2>
                        <p class =" text-muted"> Sales overview and Summary</p>
                    </div>
                </div>
            

                <div class = "col-sm-6 mt-5 d-flex justify-content-end">
                    <div class="dropdown p-1">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        View by
                        </button>
                        <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </div>


                    <div class="dropdown p-1">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Sales From
                        </button>
                        <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </div>
                </div>
            </div>

                    <hr><h2 class=' fw-bold my-4'>Draft Blogs<h2>
                    <div class="row mb-5">
                        
                        {% for object in object_list %}
                            {% if object.status == '0' %}
                            
                                <div class='d-flex card me-3 mb-3' style="width: 14rem;">
                                    <div class ="card-body text d-flex justify-content-center fs-3">
                                        {{ object.title }}</div>
                                        
                                        <div class ="card-body d-flex justify-content-center fs-5 mb-3">
                                        <a href="{% url 'adminpanel:published' pk=object.id  %}" class ="text-decoration-none text-success">Publish</a>
                                        </div>
                                        <div class ="card-body d-flex justify-content-center fs-5 mb-3">
                                            <a href="{% url 'adminpanel:unpublished' pk=object.id  %}" class ="text-decoration-none text-success">UnPublish</a>
                                        </div>
                                    
                                    <div class="card-footer d-flex justify-content-center fs-5">
                                        <a class= "text-decoration-none text-secondary" href = "/blogapp/detail/{{ object.id }}/"> More Details</a>
                                    </div>
                                </div>
                            
                            {% endif %}
                        {% endfor%}
                    </div>

                    <hr><h2 class='fw-bold my-5 '>Published Blogs<h2>
                    <div class="row mb-5">
                        
                        {% for object in object_list %}
                        {% if object.status == '1' %}
                            <div class='d-flex card me-3 mb-3' style="width: 14rem;">
                                <div class ="card-body text d-flex justify-content-center fs-3">
                                    {{ object.title }}</div>
                                    
                                    <div class ="card-body d-flex justify-content-center fs-5 mb-3">
                                    <a href="{% url 'adminpanel:unpublished' pk=object.id  %}" class ="text-decoration-none text-success">UnPublish</a>
                                    </div>
                                
                                <div class="card-footer d-flex justify-content-center fs-5">
                                    <a class= "text-decoration-none text-secondary" href = "/blogapp/detail/{{ object.id }}/"> More Details</a>
                                </div>
                            </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    
                    <hr><h2 class='fw-bold my-5'>Unpublished Blogs<h2>
                    <div class="row mb-5">
                        
                        {% for object in object_list %}
                        {% if object.status == '2' %}
                            <div class='d-flex card me-3 mb-3' style="width: 14rem;">
                                <div class ="card-body text d-flex justify-content-center fs-3">
                                    {{ object.title }}</div>
                                    
                                    <div class ="card-body d-flex justify-content-center fs-5 mb-3">
                                    </div>
                                
                                <div class="card-footer d-flex justify-content-center">
                                    <a class= "text-decoration-none text-secondary fs-5" href = "/blogapp/detail/{{ object.id }}/"> More Details</a>
                                </div>
                            </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                
        </div>
    </div>
    <br>
</section>

{% endblock %}

pep/adminpanel/templates/adminpanel/header.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-dark shadow " style="font-family: Cursive;">
    <div class="container-fluid">
      <a class="navbar-brand text-white fs-4 fw-bold"  href="{% url 'adminpanel:index' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse fs-5" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
          <li class="nav-item ">
            
            <a class="nav-link active text-white" aria-current="page" href="{% url 'blogapp:bloghome' %}">Blogs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active text-white" aria-current="page" href="{% url 'ProductApp:productlist' %}">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="#">Contact Us</a>
          </li>
        </ul>
        <ul class="navbar-nav d-flex">
            <li class="nav-item me-4 ">
              {% if request.user.is_superuser %}
              <a class="nav-link active text-white" aria-current="page" href="{% url 'adminpanel:home' %}">Admin</a>
              {% endif %}
            </li>
            <li class="nav-item ">
                <a class="nav-link active text-white" aria-current="page" href="{% url 'mypep:detail' %}">User Profile</a>
            </li>
        </ul>
        {% comment %} <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form> {% endcomment %}
      </div>
    </div>
</nav>

pep/adminpanel/templates/adminpanel/hey.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>

        {% load static%}
        <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>

    


    <section>
        <div class="col-sm-3 mx-3 mt-1"><a class= "btn btn-dark d-flex " style="width:4rem" href="{% url 'adminpanel:index' %}">Home</a>
        </div>
        <div class="d-flex row">
            
            <div class = "col-sm-2">
                <h4 class="mt-3 mx-3">Interface</h4>
                <ul class="mt-4">
                    
                    <li class="my-3 mx-3">

                        <a class="text-dark text-decoration-none" href ="{% url 'adminpanel:home' %}">OverView</a>
    
                    </li>
                    <li class="my-3 mx-3">

                        <a class="text-dark text-decoration-none fw-bold" href ="{% url 'adminpanel:userstatus' %}">User Status</a>

                    </li>


                    <li class="my-3 mx-3">
                        <a class="text-dark text-decoration-none"  href="{% url 'adminpanel:listblog' %}">
                            Blog List
                        </a>


                    </li>


                    <li class="my-3 mx-3">
                        <a class="text-dark text-decoration-none" id ="drop2" data-bs-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample2">
                            Pages
                        </a>


                    </li>
                </ul>

                

                <h4 class="mt-5 mx-3">UI Toolkits</h4>
                <ul class="mt-4">
                    <li class="my-3 mx-3">Components</li>
                    <li class="my-3 mx-3">Content</li>
                    <li class="my-3 mx-3">Forms</li>
                    <li class="my-3 mx-3">Utilities</li>
                </ul>

                <h4 class="mt-5 mx-3">Plugins</h4>
                <ul class="mt-4">
                    <li class="my-3 mx-3">Charts</li>
                    <li class="my-3 mx-3">Code Blocks</li>
                    <li class="my-3 mx-3">Data Tables</li>
                    <li class="my-3 mx-3">Data Picker</li>
                </ul>

                

            </div>

            <div class="col-md-9">
                <div class="row ">
                    <div class = "col-sm-6 ">
                        <div class ="container-xl-p-5 ms-2">
                            <h2 class ="display-6 fw-bold mb-0 mt-5">Dashboard</h2>
                            <p class =" text-muted"> Sales overview and Summary</p>
                        </div>
                    </div>
                
    
                    <div class = "col-sm-6 mt-5 d-flex justify-content-end">
                        <div class="dropdown p-1">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            View by
                            </button>
                            <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </div>
    
    
                        <div class="dropdown p-1">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Sales From
                            </button>
                            <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            

        

            
                <div class="col sm-2 ">
                    <div class ="d-flex justify-content-center">
                        <div class="card  mt-4">
                            <div class="card-header text-white bg-primary d-flex justify-content-center ">
                                <p class="fw-bold fs-4">Hello</p>
                            </div>
                            <div class="card-body ">
                                <table class="table ">
                                    <thead>
                                    <tr>
                                        
                                        <th scope="col">User Name |</th>
                                        <th scope="col">Super User Status |</th>

                                        {% if request.user.is_superuser%}
                                        <th scope="col">Change User Status</th>
                                        {% endif %}
                                    </tr>
                                    </thead>
                                    <tbody>

                                        {% for user in users %}

                                        <tr>
                                            <td>{{user}}</td>
                                            <td>{{user.is_superuser}}</td>

                                            {% if request.user.is_superuser%}
                                            <td><a class="btn btn-warning" href="{% url 'adminpanel:status' pk=user.id %}" >Change User Status</a></td>
                                            {% endif %}
                                            
                                            

                                        </tr>

                                        {% endfor %}

                                       

                                    </tbody>
                                </table>
                            </div>  
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

pep/adminpanel/templates/adminpanel/index.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% block content %}
 
<section>

    <div class="row">
        <div class ="col-md-9">
            
            <div class="d-flex justify-content-center my-5">
                <h1> <i class="fas fa-user-alt mx-3" ></i> Home</h1>
            </div>
        </div>
    </div>

</section>


{% endblock %}