pep/adminpanel/urls.py
from django.urls import path
from adminpanel.views import HomeView, AdminView, AdView, NormalView, MyUserView, MyStatusView, IndexView, ListBlog
from adminpanel import views


app_name = 'adminpanel'

urlpatterns = [
    path('home/', HomeView.as_view(), name="home"),
    path('index/', IndexView.as_view(), name="index"),
    path('getUser/', AdminView.as_view(), name="adminn"),
    path('getSuper/', AdView.as_view(), name="ad"),
    path('getNormal/', NormalView.as_view(), name="normaluser"),
    path('userstatus/', MyUserView.as_view(), name='userstatus'),
    path('status/<int:pk>', MyStatusView.as_view(), name='status'),
    path('lists/',views.ListBlog.as_view(),name='listblog'),
    path('unpublished/<int:pk>/', views.unpublished, name='unpublished'),
    path('published/<int:pk>/', views.published, name='published')
]
    

pep/blogapp/urls.py
from django.urls import path
from blogapp import views
from blogapp.views import Blogging, BlogCreate
from django.conf import settings
from django.conf.urls.static import static

app_name = "blogapp"

urlpatterns = [
    path('', views.Blogging.as_view(),name="index"),
    path('create/', views.BlogCreate.as_view(),name="create"),
    path('update/<int:pk>/',views.BlogUpdate.as_view(),name='update'),
    path('detail/<int:pk>/',views.BlogDetail.as_view(),name='detail'),
    path('delete/<int:pk>/',views.BlogDelete.as_view(),name='delete'),
    path('list/',views.BlogList.as_view(),name='list'),
    path('listHome/',views.BlogHome.as_view(),name='bloghome'),
    path('listRate/',views.BlogListRating.as_view(),name='blograte'),
    path('remove/<int:pk>/', views.remove, name='remove'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('results/', views.SearchView.as_view(), name='search'),
    path('like/<int:pk>/', views.postLike, name='like'),
    path('dislike/<int:pk>/', views.postDisLike, name='dislike'),
    path('list_user/',views.BlogListUser.as_view(),name='listuser'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pep/modules/product/ProductApp/urls.py
from django.urls import path
from modules.product.ProductApp import views

app_name = "ProductApp"

urlpatterns = [
    path('home/', views.Home, name='home'),
    path('create/', views.ProductCreate.as_view(), name="productcreate"),
    path('update/<int:pk>/', views.ProductUpdate.as_view(), name="productupdate"),
    path('detail/<int:pk>/', views.ProductDetail.as_view(), name="productdetail"),
    path('delete/<int:pk>/', views.ProductDelete.as_view(), name="productdelete"),
    path('list/', views.ProductList.as_view(), name="productlist"),
    path('order/<int:pk>', views.OrderCreate.as_view(), name="ordercreate"),
    path('order_done/', views.order_done, name="order_done"),
    path('orderlist/', views.OrderList.as_view(), name="orderlist"),
    path('orderdetail/<int:pk>/', views.OrderDetail.as_view(), name="orderdetail"),
    path('cartlist/', views.CartList.as_view(), name="cartlist"),
    path('addcart/<int:pk>', views.addcart, name="addcart"),
    path('removecart/<int:pk>', views.removecart, name="removecart"),
    path('ordercart/<int:pk>/', views.OrderCart.as_view(), name="ordercart"),
    path('updatecart/<int:pk>/', views.AddCartUpdate.as_view(), name="updatecart"),
    path('payment/<int:pk>/', views.PaymentOrder, name='payment'),
    path('paymentcart/<int:pk>/', views.PaymentCart, name='paymentcart'),
    path('paymentstatus/<int:pk>/', views.PaymentStatus, name = 'paymentstatus')
]

pep/mypep/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as pep_views
from mypep.views import MyView, SignUpView, UserLogin, ProfileUpdate, ProfileDetail, MyDetailView


app_name = "mypep"

urlpatterns = [
    path('', MyView.as_view(), name="base"),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='mypep:login'), name='logout'),

    path('update/<int:pk>', ProfileUpdate.as_view(), name='update'),

    path('detail/', MyDetailView.as_view(), name='detail'),


    path('change/', pep_views.PasswordChangeView.as_view(template_name="mypep/password_change_form.html",
                                                          success_url=reverse_lazy('mypep:password_change_done')), name='password_change'),
    path('change_done/', pep_views.PasswordChangeDoneView.as_view(template_name="mypep/password_change_done.html",),
                                                                  name='password_change_done'),

    path('reset_password/', pep_views.PasswordResetView.as_view(template_name="mypep/password_reset_form.html",success_url=reverse_lazy('mypep:password_reset_done')), 
    name = 'password_reset'),
    path('reset_password_sent/', pep_views.PasswordResetDoneView.as_view(template_name="mypep/password_reset_done.html"), 
    name = 'password_reset_done'),
    path('reset/<uidb64>/<token>', pep_views.PasswordResetConfirmView.as_view(template_name="mypep/password_reset_confirm.html",success_url=reverse_lazy('mypep:password_reset_complete')), 
    name = 'password_reset_confirm'),
    path('reset_password_complete/', pep_views.PasswordResetCompleteView.as_view(template_name="mypep/password_reset_complete.html"), 
    name = 'password_reset_complete')
]

pep/pep/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.templatetags.static import static
from django.conf.urls.static import static

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path("admin/", admin.site.urls),
    path("mypep/", include('mypep.urls')),
    path("adminpanel/", include('adminpanel.urls')),
    path("blogapp/", include('blogapp.urls')),
    path("blogcomment/", include('blogcomment.urls')),
    path("product/",include('modules.product.ProductApp.urls', namespace='product'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pep/modules/product/ProductApp/forms.py
from django import forms
from .models import ProductModel, CategoryModel, TagModel, OrderModel
from modules.models import AddressModel
from django.forms import ModelForm, TextInput

class ProductForm(forms.ModelForm):
    """
    Form to create products
    """
    class Meta:
        model = ProductModel
        fields = ['name', 'price', 'image','description', 'company', 'street', 'city', 'state', 'country', 'pin_code', 'latitude', 'longitude'  ]


class OrderForm(forms.ModelForm):
    class Meta:
        model = OrderModel
        fields = ['ordered_by',   'email', 'mobile_number', 'total_amount', 'quantity', 'street', 'city', 'state', 'country', 'pin_code', 'latitude', 'longitude']


class CartOrderForm(forms.ModelForm):
    class Meta:
        model = OrderModel
        fields = ['ordered_by',   'email', 'mobile_number', 'street', 'city', 'state', 'country', 'pin_code', 'latitude', 'longitude']

pep/modules/product/ProductApp/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views.generic.edit import CreateView,UpdateView,DeleteView,FormView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy, reverse
from .models import ProductModel, TagModel, CategoryModel, OrderModel, CartModel, StockModel, UserAddressModel, AddCartModel, CartItem, Payment
from .forms import ProductForm, OrderForm, CartOrderForm
from datetime import date
from datetime import datetime
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.http import JsonResponse


def Home(request):
    return HttpResponse("World!!!!!!")


class ProductCreate(CreateView):
    """
    Class based view to create Product
    """
    form_class = ProductForm
    template_name = "ProductApp/productmodel_form.html"
    success_url = reverse_lazy('ProductApp:productlist')

    def form_valid(self, form):
        tag_data = self.request.POST['tagname']
        tagging  = tag_data.split(',')
        category = self.request.POST['categoryname']
        data = form.save(commit=False)

        x = CategoryModel.objects.filter(title=category)
        if x :
            data.category = x[0]
        else:
            v = CategoryModel.objects.create(title=category)
            data.category = v
        data.save()

        for tag in tagging:
            try:
                var = TagModel.objects.get(name=tag)
                data.tags.add(var)
            except:
                data.tags.create(name=tag)

        return redirect('ProductApp:productlist')


class ProductUpdate(UpdateView):
    """
    Class based view to update Product
    """
    model = ProductModel
    form_class = ProductForm
    success_url = reverse_lazy('ProductApp:list')
    template_name = 'ProductApp/productmodel_update.html'

    def form_valid(self, form):
        tag_data = self.request.POST['tagname']
        tagging  = tag_data.split(' ')
        data = form.save()
        category = self.request.POST['categoryname']
        x = CategoryModel.objects.filter(title=category)
        if x :
            data.category = x[0]
        else:
            v = CategoryModel.objects.create(title=category)
            data.category = v
        
        data.save()

        for tag in tagging:
            try:
                var = ProductModel.objects.get(name=tag)
                taggers = data.tags.all()
                if var in tagging:
                    continue
                else:
                    data.tags.add(var)
            except:
                data.tags.create(name=tag)

        return redirect('ProductApp:detail', data.id)


class ProductDetail(DetailView):
    """
    Class based view for detail of Product
    """
    model = ProductModel
    template_name = "ProductApp/productmodel_detail.html"

    def get_context_data(self,  *args, **kwargs):
        context = super().get_context_data(**kwargs)
        prod_id = self.kwargs['pk']
        prod = get_object_or_404(ProductModel, id=self.kwargs['pk'])
        cart = CartModel.objects.get(product=prod)
        cart.save()
        lst=[]
        a = CartItem.objects.all()
        for i in a:
            lst.append(i.product.name)
        context["quantity"] = cart.quantity
        context["cart_items"] = lst
        return context


# function to delete a product by authorized users only
def remove(request, pk):
    product = ProductModel.objects.get(id=pk)
    if product.blogger == request.user or request.user.is_staff:
        return redirect('ProductApp:productdelete', pk=product.id)
    else:
        return HttpResponse("not authorized!!!!")
    return redirect('ProductApp:productdetail', pk=product.id)


# function to edit a product by authorized users only
def edit(request, pk):
    product=ProductModel.objects.get(id=pk)
    if product.blogger == request.user or request.user.is_staff:
        return redirect('ProductApp:productupdate',pk=product.id)
    else:
        return HttpResponse("not authorized to update!!!!")
    return redirect('ProductApp:productdetail', pk=product.id)


class ProductList(ListView):
    """
    Class based view to list out Products
    """
    model = ProductModel

    def get_context_data(self,  *args, **kwargs):
        context = super().get_context_data(**kwargs)
        tshirts = ProductModel.objects.filter(category__title='T-Shirts')
        shirt = ProductModel.objects.filter(category__title='Shirt')
        jacket = ProductModel.objects.filter(category__title='Jacket')
        jeans = ProductModel.objects.filter(category__title='Jeans')
        context['tshirts'] = tshirts
        context['shirt'] = shirt
        context['jacket'] = jacket
        context['jeans'] = jeans
        return context


class ProductDelete(DeleteView):
    """
    Class based view to delete Product
    """
    model = ProductModel
    template_name = 'ProductApp/productmodel_confirm.html'
    success_url = reverse_lazy('ProductApp:productlist')


def order(self, request):
    return redirect('ProductApp:productlist')


class OrderCreate(CreateView):
    """
    Class based view to create a order for a product
    """
    form_class = OrderForm
    template_name = 'productapp/ordermodel_form.html'
    success_url = reverse_lazy('ProductApp:order_done')

    def form_valid(self,form):
        order = form.save()
        pk = self.kwargs['pk']
        product = ProductModel.objects.get(id=pk)
        order.cart = CartModel.objects.get(product=product)
        order.save()
        cart = CartModel.objects.get(product=product)
        cart.quantity = cart.quantity - order.quantity
        cart.save()
        address= self.request.POST['add1']
        location = UserAddressModel.objects.get(street=address)
        order.street = location.street
        order.city = location.city
        order.state = location.state
        order.country = location.country
        order.pin_code = location.pin_code
        order.latitude = location.latitude
        order.longitude = location.longitude
        order.save()
        return redirect('ProductApp:payment', pk=product.id)

    def get_context_data(self,  *args, **kwargs):
        context = super().get_context_data(**kwargs)
        prod_id = self.kwargs['pk']
        prod = get_object_or_404(ProductModel, id=self.kwargs['pk'])
        p = prod.name
        cart = CartModel.objects.get(product=prod)
        cart.save()
        address = UserAddressModel.objects.all()
        context["prod"] = p
        context["quantity"] = cart.quantity
        context["address"] = address
        return context


# function to return the page after order is done
def order_done(request):
    return render(request, 'productapp/order_done.html')


class OrderList(ListView):
    """
    Class based view to list out all the orders
    """
    model = OrderModel

    def get_context_data(self,  *args, **kwargs):
        context = super().get_context_data(**kwargs)
        p = Payment.objects.all()
        lst = []
        for i in p:
            lst.append(i.order)
        context['p'] = p
        context['lst'] = lst
        return context


class OrderDetail(DetailView):
    """
    Class based view for details of a order
    """
    model = OrderModel

    def get_context_data(self,  *args, **kwargs):
        context = super().get_context_data(**kwargs)
        cartlist = AddCartModel.objects.all()
        context['cartlist'] = cartlist
        return context


class CartList(ListView):
    """
    Class based view to list out the cart items
    """
    model = AddCartModel

    def get_context_data(self,  *args, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = AddCartModel.objects.all()
        amount = 0
        for item in cart:
            for i in item.product.all():
                amount = amount + ( i.product.price * i.quantity)
        items = CartItem.objects.all().count()
        context['amount'] = amount
        context['items'] = items
        return context


# function to add item in cart
def addcart(request, pk):
    product = ProductModel.objects.get(id=pk)
    cart = AddCartModel.objects.get(id=31)
    b = CartItem.objects.create(product=product)
    b.save()
    products=[]
    a = CartItem.objects.all()
    for q in a:
        products.append(q.product)
    for p in products:
        try:
            var = CartItem.objects.get(product=p)
            cart.product.add(var)
        except:
            cart.product.create(product=p)
    cart.save()
    c = CartItem.objects.get(product=product)
    c.quantity = 1
    c.save()
    return redirect('ProductApp:productdetail', pk=product.id)


# function to remove item from cart
def removecart(request, pk):
    product = ProductModel.objects.get(id=pk)
    item = CartItem.objects.get(product=product)
    item.delete()
    return redirect('ProductApp:cartlist')


class AddCartUpdate(UpdateView):
    """
    Class based view to update cart
    """
    model = CartItem
    fields = ['quantity']
    template_name = 'ProductApp/addcartmodel_update.html'

    def form_valid(self, form):
        form.save()
        return redirect('ProductApp:cartlist')


class OrderCart(CreateView):
    """
    Class based view to create a order for a cart
    """
    form_class = CartOrderForm
    template_name = 'productapp/cartordermodel_form.html'
    success_url = reverse_lazy('ProductApp:order_done')

    def form_valid(self,form):
        order = form.save()
        pk = self.kwargs['pk']
        cart = AddCartModel.objects.get(id = 31)
        order.addcart = cart
        address= self.request.POST['add11']
        location = UserAddressModel.objects.get(street=address)
        order.street = location.street
        order.city = location.city
        order.state = location.state
        order.country = location.country
        order.pin_code = location.pin_code

pep/modules/product/ProductApp/templates/ProductApp/addcartmodel_update.html
{% extends 'ProductApp/base.html' %}
{% load static %}

{% block style %}
{% load static %}

{% endblock %}

{% block content %}
{% load widget_tweaks %}

<div class='text-center my-5'>
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' class='btn btn-outline-dark' value='Submit'>
    </form>
</div>

{% endblock %}

pep/modules/product/ProductApp/templates/ProductApp/header.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-dark shadow " style="font-family: Cursive;">
    <div class="container-fluid">
      <a class="navbar-brand text-white fs-4 fw-bold"  href="{% url 'ProductApp:home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse fs-5" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
          <li class="nav-item ">
            
            <a class="nav-link active text-white" aria-current="page" href="{% url 'ProductApp:productlist' %}">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'blogapp:bloghome' %}">Blogs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="">About Us</a>
          </li>
        </ul>
        <ul class="navbar-nav d-flex ">
            <li class="nav-item me-4 ">
              {% if request.user.is_superuser %}
              <a class="nav-link active text-white" aria-current="page" href="{% url 'adminpanel:home' %}">Admin</a>
              {% endif %}
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle  text-white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                User Profile
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'ProductApp:cartlist' %}">Cart</a>
                <a class="dropdown-item" href="{% url 'ProductApp:orderlist' %}">Order</a>
                <a class="dropdown-item" href="{% url 'mypep:detail' %}">Profile</a>
              </div>
            </li>

        </ul>

      </div>
    </div>
</nav>

<style>
  .dropdown:hover .dropdown-menu {
    display: block;
  }
</style>

pep/modules/product/ProductApp/templates/ProductApp/ordermodel_list.html
{% extends 'ProductApp/base.html' %}
{% load static %}

{% block style %}
{% load static %}

{% endblock %}

{% block content %}
{% load widget_tweaks %}

<div class='container-fluid'>

    <div id='products' class='row text-center '>
        <h2 class='my-3 fw-bold' style="text-shadow:4px 4px #d3d2d4";>ORDERS</h2>
    </div>

    <div  class='row'>

        {% for object in object_list %}
        <div class="col-md-3 col-sm-6">

            <div class="card shadow-lg my-5" style="width: 18rem;  margin-left: 15%">

                <div class="card-body">
                    <h5 class="card-title">{% if object.cart %} {{ object.cart.product }} {% else %} Cart {% endif %}</h5>
                    <div class='card-title content'>
                        <h6>Ordered By - {{ object.ordered_by }}</h6>
                    </div>
                    <h6 class="card-text">Quantity - {{ object.quantity }}</h6>

                </div>

                <div class='card-footer' >
                    {% for i in p %}

                        {% if i.order == object %}

                            {% if i.status == '0' %}

                                <a href='' class = 'btn btn-success'>Paid</a>

                            {% else %}
                                {% if i.order.addcart %}
                                <a href='{% url "ProductApp:paymentcart" pk=i.order.id %}' class = 'btn btn-warning'>Pay Now</a>
                                {% elif i.order.cart %}
                                <a href='{% url "ProductApp:payment" pk=i.order.id %}' class = 'btn btn-warning'>Pay Now</a>
                                {% endif %}
                            {% endif %}

                        {% endif %}

                    {% endfor %}

                    {% if object not in lst %}
                            {% if object.addcart %}
                            <a href='{% url "ProductApp:paymentcart" pk=object.id %}' class = 'btn btn-warning'>Pay Now</a>
                            {% elif object.cart %}
                            <a href='{% url "ProductApp:payment" pk=object.id %}' class = 'btn btn-warning'>Pay Now</a>
                            {% endif %}
                    {% endif %}

                    <a class='btn btn-outline-primary mx-2' href='{% url "ProductApp:orderdetail" pk=object.id %}' style="text-decoration:none"> Order Details</a>
                </div>

            </div>

        </div>
        {% endfor %}

    </div>
</div>

{% endblock %}

pep/modules/product/ProductApp/templates/ProductApp/payment.html
{% extends 'ProductApp/base.html' %}
{% load static %}

{% block style %}
{% load static %}

{% endblock %}

{% block content %}
{% load widget_tweaks %}

<div class='container-fluid'>
    <div class='row d-flex justify-content-center'>
        <div class='card shadow-lg my-5' style='max-width:20rem'>
            <div class='card-header text-center '>
                <h3 class='fw-bold'>Payment</h3>
            </div>
            <h4 class='my-2 text-center'>{{ product }}</h4>
            <h4 class='my-2 text-center'>Total Amount - Rs. {{ amount }}</h4>
            <div class='card-body'>
                <div id="paypal-button-container"></div>
            </div>
    
        </div>
    </div>
</div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AeRsqR1vY9xZmqJHZUAkROeY8KaU8LtshFolBdM5HBxThsWa3Y4CFol8YCm0Q970MLjxpFD-S1-D3Nco&currency=USD"></script>

    <script>
        var total = '{{ amount }}'
        console.log(total)
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: parseFloat(total * 0.001).toFixed(2)
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(orderData) {
                    // Successful capture! For demo purposes:
                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                    var transaction = orderData.purchase_units[0].payments.captures[0];
                    alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
        
                    $.ajax({
                        type: "POST",
                        url: "{% url 'ProductApp:paymentstatus' pk=order.id %}",   
                        data: {csrfmiddlewaretoken: '{{ csrf_token }}',
                              text: "this is my test view"},   /* Passing the text data */
                        success:  function(response){
                               alert(response);
                               console.log(data)
                           }
                     });
                    location.href = 'http://127.0.0.1:8000/product/orderlist/';
   
                });
            }

        }).render('#paypal-button-container');

    </script>

{% endblock %}

pep/modules/product/ProductApp/templates/ProductApp/productmodel_detail.html
{% extends 'ProductApp/base.html' %}
{% load static %}

{% block style %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">
{% endblock %}

{% block content %}

<div class='row my-4'>
  <div class='col-md-6 d-flex justify-content-center'>

    <div class='mt-5' >
      <h2 class='fw-bold' style='text-shadow:4px 4px #d3d2d4;'>{{ object.name }}</h2>
      <br>
      <a class='btn btn-secondary fw-bold'>Rs. {{ object.price }}</a>
      <br><br>

      <div class='card bg-dark  text-white' style='font-family:Times'>
        <div class='fs-4 ms-2 my-2 fw-bold card-text'>Description </div>
        <div class='fs-5 ms-2 my-2'> {{ object.description }}</div>
      </div>
      <br>
      <table style="font-family:Times; font-size:130%" class="table ">

        <tr>
          <th scope="row">Category</th>
          <td>{{ object.category }}</td>
        </tr>
        <tr>
          <th scope="row">Tags</th>
          {% for i in object.tags.all  %}
          <td colspan="2">{{ i.name }}</td>
          {% endfor %}
        </tr>
        <tr>
          <th scope="row">Company</th>
          <td>{{ object.company }}</td>
        </tr>
        <tr>
            <th scope="row">Mfg. Date</th>
            <td>{{ object.manufacturing_date }}</td>
        </tr>
        <tr>
            <th scope="row">Expiry Date</th>
            <td>{{ object.expiry_date }}</td>
        </tr>
        <tr>
          <th scope="row">Created Date</th>
          <td>{{ object.created_at }}</td>
        </tr>
        <tr>
          <th scope="row">Updated Date</th>
          <td>{{ object.updated_at }}</td>
        </tr>

        <tr>
          {% if quantity > 0 %}
          <th scope="row"><a class="btn btn-primary text-decoration-none" style="box-shadow:5px 5px #d3d2d4" href="{% url 'ProductApp:ordercreate' pk=object.id %}">Order This Product</a></th>
            {% if object.name not in cart_items %}

            <th scope="row">
                <form method = "POST" action = {% url 'ProductApp:addcart' pk=object.id %} enctype = "multipart/form-data">
                  {% csrf_token%}
                  <input type="submit" class='btn btn-outline-dark' name='add' value="Add To Cart" style="width:12rem">
                </form>
            </th>

            {% else %}
            <th scope="row">
              <input type="button" class='btn btn-dark' value=" Added To Cart "   style="width:12rem">
            <th>
            {% endif %}
          {% else %}

          <th scope="row"><a class="btn btn-danger text-decoration-none" >Out of Stock</a></th>
          {% endif %}
        </tr>

      </table> 
    </div>
  </div>

  <div class='col-md-6 d-flex justify-content-center'>
    <div class='mt-5'>
      <img src="{{ object.image.url }}" class="img-fluid rounded shadow-lg p-3 mb-5 bg-white" style="max-width:80%;max-height:80%;">
      <div class='fs-4 ' style='font-family:cursive; '>{{ object.street }}, 
        {{ object.city }}, 
        {{ object.state }},<br> 
        {{ object.country }}- 
        {{ object.pin_code }}
      </div>
    </div>
  </div>
  <div class='container mb-4 d-flex justify-content-center'>

    {% if request.user == object.user or request.user.is_staff %}
    <div class='d-flex justify-content-between'>
        <a class="btn btn-success  mb-2 text-decoration-none" style="box-shadow:5px 5px #d3d2d4" href="{% url 'ProductApp:productupdate' pk=object.pk %}">Update</a>
        <a class=" btn btn-warning ms-2  mb-2 text-decoration-none" style="box-shadow:5px 5px #d3d2d4" href="{% url 'ProductApp:productdelete' pk=object.pk %}">Delete</a>
    </div>
    {% endif %}

  </div>
</div>

<script>
  function myFunction() {
    var x = document.getElementById("add");
    var y = document.getElementById("added");

      if (x.style.display == "none") {
          x.style.display = "block";
          y.style.display = "none";
          document.getElementById("myBtn").value = "Clickddd";
      } else {
          x.style.display = "none";
          y.style.display = "block";
          document.getElementById("myBtn").value = "Show Less Comments";
      }
  }
</script>

{% endblock %}