pep/blogapp/urls.py
from django.urls import path
from blogapp import views
from blogapp.views import Blogging, BlogCreate
from django.conf import settings
from django.conf.urls.static import static

app_name = "blogapp"

urlpatterns = [
    path('', views.Blogging.as_view(),name="index"),
    path('create/', views.BlogCreate.as_view(),name="create"),
    path('update/<int:pk>/',views.BlogUpdate.as_view(),name='update'),
    path('detail/<int:pk>/',views.BlogDetail.as_view(),name='detail'),
    path('delete/<int:pk>/',views.BlogDelete.as_view(),name='delete'),
    path('list/',views.BlogList.as_view(),name='list'),
    path('listHome/',views.BlogHome.as_view(),name='bloghome'),
    path('listRate/',views.BlogListRating.as_view(),name='blograte'),
    path('remove/<int:pk>/', views.remove, name='remove'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('results/', views.SearchView.as_view(), name='search'),
    path('like/<int:pk>/', views.postLike, name='like'),
    path('dislike/<int:pk>/', views.postDisLike, name='dislike'),
    path('list_user/',views.BlogListUser.as_view(),name='listuser'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pep/pep/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.templatetags.static import static
from django.conf.urls.static import static

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path("admin/", admin.site.urls),
    path("mypep/", include('mypep.urls')),
    path("adminpanel/", include('adminpanel.urls')),
    path("blogapp/", include('blogapp.urls')),
    path("blogcomment/", include('blogcomment.urls')),
    path("product/",include('modules.product.ProductApp.urls', namespace='product'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pep/blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class TagBlog(models.Model):
    """
        TagBlog model for tags of blog
    """
    name = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Function to return name on table
    def __str__(self):
        return self.name


class BlogCategory(models.Model):
    title =  models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField( unique=True)

    # Slugify Function
    def save(self, *args, **kwargs):
      if not self.slug:
         self.slug = slugify(self.title)
      return super().save(*args, **kwargs)

    # Function to return title on table
    def __str__(self):
        return self.title


class PostBlog(models.Model):
    """
        PostBlog model for blog details
    """
    STATUS_CHOICES = (
        ('0', 'Draft'),
        ('1', 'Publish'),
        ('2', 'Unpublish')
    )
    title = models.CharField(max_length=250)
    content = models.TextField(max_length=300, null=True, blank=True)
    image = models.ImageField(upload_to='blog', default="", null = True, blank=True)
    blogger = models.ForeignKey(User, related_name='postblog_blogger', on_delete=models.CASCADE)
    tags = models.ManyToManyField(TagBlog, related_name="postblog_tags")
    category = models.ForeignKey(BlogCategory, related_name="postblog_category", on_delete=models.CASCADE, null = True, blank=True )
    status = models.CharField(max_length=1, choices = STATUS_CHOICES, null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='bloglike_user')
    dislikes = models.ManyToManyField(User, related_name='blogdislike_user')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(auto_now=True)
    slug = models.SlugField( unique=True)

    # Function to return number of likes
    def number_of_likes(self):
        return self.likes.count()

    # Function to return number of dislikes
    def number_of_dislikes(self):
        return self.dislikes.count()

    # Function to return unique slug
    def unique_slug(self):
        unique_slugg = slugify(self.title)
        num = 1
        while PostBlog.objects.filter(slug=unique_slugg).exists():
            unique_slugg = "{}-{}".format(unique_slugg,num)
            num += 1
            break
        return unique_slugg

    # Slugify Function
    def save(self, *args, **kwargs):
      if not self.slug:
         self.slug = self.unique_slug()
      return super().save(*args, **kwargs)

    # Function to return title on table
    def __str__(self):
        return self.title

pep/blogapp/forms.py
from django import forms
from .models import BlogCategory, PostBlog, TagBlog
from django.forms import ModelForm, TextInput

class BlogForm(forms.ModelForm):
    """
    Form to create blogs
    """
    class Meta:
        model = PostBlog
        fields = ['title', 'content', 'image','category','status']


class StatusForm(forms.Form):
    Published  = forms.CharField()
    Unpublished  = forms.CharField()

pep/blogapp/views.py
from django.shortcuts import render,redirect, HttpResponse
from .models import BlogCategory, PostBlog, TagBlog
from .forms import BlogForm
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from blogcomment.forms import BlogCommentForm, BlogRatingForm
from blogcomment.models import BlogCommentModel, BlogRatingModel
from mypep.models import ProfileModel
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.db.models import Avg
from decimal import Decimal
from django.db.models import Func
from django.utils import timezone
import datetime
import operator
from operator import itemgetter
from decimal import Decimal
from django.template.loader import render_to_string


class Blogging(View):
    """
    Home page view
    """
    # Function to render home page

    def get(self, request):
        return render(request, 'blogapp/home.html')


class BlogCreate(LoginRequiredMixin, CreateView):
    """
    To create a blog form
    """
    login_url = '/mypep/login'
    redirect_field_name = 'login'
    form_class = BlogForm
    template_name = "blogapp/postblog_form.html"
    success_url = reverse_lazy('blogapp:list')

    # Function if the form is valid
    def form_valid(self, form):
        tag_data = self.request.POST['tagname']
        tagging = tag_data.split(',')
        data = form.save(commit=False)
        data.blogger = self.request.user
        data.status = 0
        data.save()
        for tag in tagging:
            try:
                var = TagBlog.objects.get(name=tag)
                data.tags.add(var)
            except:
                data.tags.create(name=tag)
        return redirect('blogapp:list')


class BlogUpdate(LoginRequiredMixin, UpdateView):
    """
    To update a blog form
    """
    login_url = '/mypep/login'
    redirect_field_name = 'login'
    model = PostBlog
    template_name = "blogapp/postblog_update.html"

    # Function to perform operations if the form is valid
    def form_valid(self, form):
        tag_data = self.request.POST['tagname']
        tagging = tag_data.split(' ')
        data = form.save()
        data.published_date = None
        data.save()
        for tag in tagging:
            try:
                var = TagBlog.objects.get(name=tag)
                taggers = data.tags.all()
                if var in tagging:
                    continue
                else:
                    data.tags.add(var)
            except:
                data.tags.create(name=tag)

        status_data = self.request.POST['status']
        return redirect('blogapp:detail', data.id)

    # dispatch function to show particular fields
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            self.fields = ['title', 'content', 'image', 'category', 'status']
        else:
            self.fields = ['title', 'content', 'image', 'category']
        return super().dispatch(request, *args, **kwargs)


class BlogDetail(DetailView):
    """
    class to show blog details
    """
    model = PostBlog
    form_class = BlogForm
    template_name = "blogapp/postblog_detail.html"

    # function to get context data
    def get_context_data(self,  *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = BlogCommentForm()
        blog_id = self.kwargs['pk']
        blog = get_object_or_404(PostBlog, id=self.kwargs['pk'])
        comments = BlogCommentModel.objects.order_by(
            '-created_at').filter(blogpost=blog_id)[:5]
        like_number = blog.number_of_likes()
        like = False
        if blog.likes.filter(id=self.request.user.id).exists():
            like = True
        dislike_number = blog.number_of_dislikes()
        dislike = False
        if blog.dislikes.filter(id=self.request.user.id).exists():
            dislike = True
        ratings = BlogRatingModel.objects.filter(post=blog_id)
        lst = []
        for i in ratings:
            lst.append(i.rater)
        if self.request.user not in lst:
            context["ratingform"] = BlogRatingForm()
        rating_avg = BlogRatingModel.objects.filter(
            post=blog_id).aggregate(Avg('rating'))
        rate = {}
        rate = rating_avg
        rate_avg = rate.get('rating__avg')
        context["comment_list"] = comments
        context["like_number"] = like_number
        context["like"] = like
        context["dislike_number"] = dislike_number
        context["dislike"] = dislike
        context["list"] = lst
        context["rate_avg"] = rate_avg
        return context


# this function is called if the post is liked
def postLike(request, pk):
    blog = PostBlog.objects.get(id=pk)

    if blog.likes.filter(id=request.user.id).exists():
        blog.likes.remove(request.user)
    else:
        if blog.dislikes.filter(id=request.user.id).exists():
            blog.dislikes.remove(request.user)
        blog.likes.add(request.user)

    return redirect('blogapp:detail', pk=blog.id)


# this function is called if the post is disliked
def postDisLike(request, pk):
    blog = PostBlog.objects.get(id=pk)
    if blog.dislikes.filter(id=request.user.id).exists():
        blog.dislikes.remove(request.user)
    else:
        if blog.likes.filter(id=request.user.id).exists():
            blog.likes.remove(request.user)
        blog.dislikes.add(request.user)

    return redirect('blogapp:detail', pk=blog.id)


# Function to delete a blog
def remove(request, pk):
    blog = PostBlog.objects.get(id=pk)
    if blog.blogger == request.user or request.user.is_staff:
        return redirect('blogapp:delete', pk=blog.id)
    else:
        return HttpResponse("not authorized!!!!")
    return redirect('blogapp:detail', pk=blog.id)


# Function to update a blog
def edit(request, pk):
    blog = PostBlog.objects.get(id=pk)
    if blog.blogger == request.user or request.user.is_staff:
        return redirect('blogapp:update', pk=blog.id)
    else:
        return HttpResponse("not authorized to update!!!!")


class SearchView(ListView):
    """
    Class to get the search results
    """
    model = PostBlog

    # get Function to get the search results in blog list
    def get(self, request):
        query = self.request.GET['q']
        result = PostBlog.objects.filter(title__icontains=query)
        msg = None
        if not result:
            msg = "Result Not Found"
        searched = {'result': result, 'msg': msg}
        return render(request, 'blogapp/postblog_list.html', searched)


class BlogDelete(DeleteView):
    """
    Class for deleting a blog
    """
    model = PostBlog
    template_name = "blogapp/postblog_confirm_delete.html"
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('blogapp:create')


class BlogHome(ListView):
    """
    class to show the list of blogs
    """
    model = PostBlog
    template_name = "blogapp/postblog_home.html"

    # function to show latest 4 published blogs
    def get_context_data(self,  *args, **kwargs):
        context = super().get_context_data(**kwargs)
        blog_list = PostBlog.objects.order_by(
            '-created_at').filter(status=1)[:4]
        count = PostBlog.objects.filter(status=1).count()
        lst = []
        publish = PostBlog.objects.filter(status=1)
        posts = PostBlog.objects.all()
        for p in posts:
            rating = BlogRatingModel.objects.filter(
                post=p.id).aggregate(Avg('rating'))
            if not rating['rating__avg']:
                rating['rating__avg'] = 0
            rating['rating__avg'] = '{:0.2f}'.format(rating['rating__avg'])
            post_dict = {'post': p, 'rating': rating['rating__avg']}
            lst.append(post_dict)
        lst.sort(key=operator.itemgetter('rating'), reverse=True)
        blog_list_rating = BlogRatingModel.objects.order_by('-rating')[:4]
        context['count'] = count
        context['blog_list'] = blog_list
        context['blog_list_rating'] = blog_list_rating
        context['lst'] = lst[:4]
        return context


class BlogList(ListView):
    """
    class to show the list of blogs
    """
    model = PostBlog
    form_class = BlogForm
    template_name = "blogapp/postblog_list.html"

    # function to show only published blogs
    def get_context_data(self,  *args, **kwargs):
        context = super().get_context_data(**kwargs)
        blog_list = PostBlog.objects.order_by(
            '-created_at').filter(status=1)[:4]
        context['blog_list'] = blog_list
        return context


class BlogListRating(ListView):
    """
    class to show the list of blogs according to ratings
    """
    model = PostBlog
    form_class = BlogForm
    template_name = "blogapp/postblog_list.html"

    # function to pass context to show only published blogs sorted according to ratings
    def get_context_data(self,  *args, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = PostBlog.objects.filter(status=1)
        lst = []
        for p in posts:
            rating = BlogRatingModel.objects.filter(
                post=p.id).aggregate(Avg('rating'))
            if not rating['rating__avg']:
                rating['rating__avg'] = 0
            post_dict = {'post': p, 'rating': rating['rating__avg']}
            lst.append(post_dict)
        lst.sort(key=operator.itemgetter('rating'), reverse=True)
        blog_list = []
        for k in lst:
            blog_list.append(k['post'])
        context['blog_list'] = blog_list
        return context


class BlogListUser(ListView):
    """
    class to show the list of blogs
    """
    model = PostBlog

pep/blogapp/templates/blogapp/home.html
<h1>hello world !!!!</h1>

pep/blogapp/templates/blogapp/postblog_confirm_delete.html
{% extends 'adminpanel/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/delete.css' %}">
{% endblock%}

{% block content %}

<div class="container d-flex jutify-content-center my-5 p-5">
    <form method="post">
        {% csrf_token %}
        <h2>Are you sure you want to delete "{{ object }}"?</h2> 
            <input type="submit" value="Confirm">
    </form>
</div>

{% endblock %}

pep/blogapp/templates/blogapp/postblog_home.html
{% extends 'adminpanel/base.html' %}
{% load static %}

{% block style %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bloghome.css' %}">
{% endblock %}

{% block content %}

<div class="container-fluid">
    {% if count > 4 %}
    
        <div class="row d-flex justify-content-end me-5" >
            <h3 class='fw-bold text-center mt-4' style="text-shadow:4px 4px #d3d2d4";>Blogs</h3>
            <a href="{% url 'blogapp:list' %}" class="btn btn-primary my-4 fs-5 ms-5" style='margin-right:100px; max-width:7rem;max-height:2.7rem;'>Blog List</a>
        </div>
        {% endif %}
        <div id='row1' class="row d-flex mt-2 justify-content-around" style="">
            
                {% for obj in blog_list %}
                <div id='cardd' class="card me-4 mb-4 shadow-lg p-3 mb-5 bg-white rounded" style="">
                    <div class="card-header bg-dark text-white fs-3 fw-bold">{{ obj.title }}</div>
                    <div class='card-body'>

                        <h5 class="card-title">{{ obj.published_date }}</h5>
                        <img src="{% if obj.image %} {{ obj.image.url }} {% endif %}" class="rounded" style ="max-height:100%; max-width:100%;">
                        <p class="card-text" >
                        {{ obj.content|truncatechars:75 }}
                        </p>

                    </div>

                </div>
               
            {% endfor %}
        
    </div>

    <hr>

    {% if count > 4 %}
    <div class="row d-flex justify-content-end me-4">
        <h3 class='fw-bold  text-center mt-4' style="text-shadow:4px 4px #d3d2d4";>Blogs According to Ratings</h3>
        <a href="{% url 'blogapp:blograte' %}" class="btn btn-primary my-4 fs-5 ms-5" style='margin-right:100px; max-width:7rem;max-height:2.7rem;'>Blog List</a>
    </div>
    {% endif %}
    <div  id='row2' class="row d-flex mt-2 justify-content-around" style="">
        
            {% for ob in lst %}
            <div id='carddd' class="card me-4 mb-4 shadow-lg p-3 mb-5 bg-white rounded" style="">
                <div class="card-header bg-dark text-white fs-3 fw-bold">{{ ob.post.title }}</div>
                <div class='card-body'>

                    <h5 class="card-title">{{ ob.post.published_date }}</h5>
                    <img src="{% if ob.post.image %} {{ ob.post.image.url }} {% endif %}" class="rounded" style ="max-height:100%; max-width:100%;">
                    <p class="card-text" >
                    {{ ob.post.content|truncatechars:75 }}
                    </p>
                    <hr>
                    Rating :- {{ ob.rating }}
                </div>

            </div>
            
            {% endfor %}
        
    </div>
</div>

<style>

    #row1{
        margin-left:100px;
        margin-right:100px;
    }
    
    #cardd{
        max-width:18rem;
    }

    #row2{
        margin-left:100px;
        margin-right:100px;
    }
    
    #carddd{
        max-width:18rem; 
        max-height:26rem;
    }
    
    @media screen and (max-width:850px){
        #row1{
            margin-left:50px;
            margin-right:50px;
        }
        
    }

    @media screen and (max-width:750px){
        #row1{
            margin-left:50px;
            margin-right:50px;
        }

        #cardd{
            max-width:14rem;
        }
        
    }

    @media screen and (max-width:630px){
        #row1{
            margin-left:20px;
            margin-right:20px;
        }

        #cardd{
            max-width:14rem;
        }
        
    }

    @media screen and (max-width:561px){
        #row1{
            margin-left:20px;
            margin-right:20px;
        }

        #cardd{
            max-width:12rem;
        }
        
    }
    @media screen and (max-width:500px){
        #row1{
            margin-left:20px;
            margin-right:20px;
        }

        #cardd{
            max-width:24rem;
        }
        
    }


    @media screen and (max-width:850px){
        #row2{
            margin-left:50px;
            margin-right:50px;
        }
        
    }

    @media screen and (max-width:750px){
        #row2{
            margin-left:50px;
            margin-right:50px;
        }

        #carddd{
            max-width:14rem;
        }
        
    }

    @media screen and (max-width:630px){
        #row2{
            margin-left:20px;
            margin-right:20px;
        }

        #carddd{
            max-width:14rem;
        }
        
    }

    @media screen and (max-width:561px){
        #row2{
            margin-left:20px;
            margin-right:20px;
        }

        #carddd{
            max-height:30rem;
            max-width:12rem;
        }
        
    }
    @media screen and (max-width:500px){
        #row2{
            margin-left:20px;
            margin-right:20px;
        }

        #carddd{
            max-height:30rem;
            max-width:24rem;
        }
        
    }


</style>

{% endblock %}

pep/blogapp/templates/blogapp/postblog_list.html
{% extends 'adminpanel/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
{% endblock %}

{% block content %}

<section>

    <div class="container-fluid d-flex">
        <div class="row ">
            <div class="col-sm-3 d-flex align-items-center bg-dark">
                <div class="row" style="font-family:Times; max-width:114%;">
                    <div class="card bg-warning my-4" >
                        <h3 class="fw-bold p-5">
                            House of Blogs</h3>
                    </div>
                    <div class="card bg-dark my-4 d-flex justify-content-center" >
                        <h2 class="fw-bold mx-5 p-2">
                            <a href="{% url 'blogapp:create' %}" class="btn  btn-success">Create A Blog</a></h2>
                    </div>
                </div>
            </div>

            <div class="d-flex col-sm-6 justify-content-center vh-100 overflow-auto">
                <div class="row" >
                    <nav class="navbar ms-4 mt-3 bg-light">
                        <div class="container-fluid">
                          <form class="" action="{% url 'blogapp:search' %}" role="search" method="get">
                            <input class="form-control me-2 mb-1" name="q" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                          </form>
                        </div>
                    </nav>

                    {% if result %}
                        {% for res in result %}
                        <div class="col-md-9 mx-3 d-flex justify-content-center">
                            <div class="card my-4 shadow p-3 mb-5 bg-white rounded">
                                <div class="card-header bg-dark text-white fs-3 fw-bold">{{ res.title }}</div>
                                <div class='card-body'>
                                    
                                    <h5 class="card-title">{{ res.blogger }}</h5>
                                    <h5 class="card-title">{{ res.published_date }}</h5>
                                    <img src="{% if res.image %} {{ res.image.url }} {% endif %}" class="rounded" style ="max-height:100%; max-width:100%;">
                                    <p class="card-text" >
                                    {{ res.content|truncatechars:75 }}
                                    </p>
                                    
                                    <a href="{% url 'blogapp:detail' pk=res.id %}" class="btn btn-primary">Read More</a>
                                </div>
                                <div class="card-footer">Category :- {{ obj.category }}
                                    <br>
                                    {% for i in res.tags.all  %}
                                    Tags :- {{ i.name }}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>


                        {% endfor %}

                    {% endif %}

                    {% if msg %}
                    {{ msg }}
                    {% endif %}

                    {% for obj in blog_list %}

                        <div class="col-md-9 mx-3 d-flex justify-content-center">
                            <div class="card my-4 shadow-lg p-3 mb-5 bg-white rounded">
                                <div class="card-header bg-dark text-white fs-3 fw-bold">{{ obj.title }}</div>
                                <div class='card-body'>
                                    
                                    <h5 class="card-title">{{ obj.blogger }}</h5>
                                    <h5 class="card-title">{{ obj.published_date }}</h5>
                                    <img src="{% if obj.image %} {{ obj.image.url }} {% endif %}" class="rounded" style ="max-height:100%; max-width:100%;">
                                    <p class="card-text" >
                                    {{ obj.content|truncatechars:75 }}
                                    </p>
                                    
                                    <a href="{% url 'blogapp:detail' pk=obj.id %}" class="btn btn-primary">Read More</a>
                                </div>
                                <div class="card-footer">Category:- {{ obj.category }}
                                    <br>
                                    {% for i in obj.tags.all  %}
                                    Tags :- {{ i.name }}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    
                
                    {% endfor %}
                </div>
            </div>
            
            <div class="bg-dark col-sm-3 d-flex align-items-center">
                <div class="row d-flex ">
                    
                        <img src="{% static 'images/picc.jpg' %}" class="rounded p-4 mt-4" alt="Cinque Terre" style="max-width:100%;max-height:100%; border-radius: .50rem;" >                         
                    
                </div>
            </div>
            
        </div>
    </div>
</section>


{% endblock %}

pep/blogapp/templates/blogapp/postblog_listuser.html
{% extends 'adminpanel/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
{% endblock %}

{% block content %}

<section>
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 d-flex align-items-center bg-dark">
                <div class="row d-flex " style="font-family:Times; max-width:113%;">
                    <div class="card bg-warning my-4" >
                        <h3 class="fw-bold p-5">
                            House of Blogs</h3>
                        
                    </div>
                    <div class="card bg-dark my-4 d-flex justify-content-center" >
                        <h2 class="fw-bold mx-5 p-2">
                            <a href="{% url 'blogapp:create' %}" class="btn  btn-success">Create A Blog</a></h2>

                    </div>
                </div>
            </div>
            <div class="d-flex col-sm-6 justify-content-center vh-100 overflow-auto">
                <div class="row" >
                    <nav class="navbar ms-4 mt-3 bg-light">
                        <div class="container-fluid">
                          <form class="d-flex" action="{% url 'blogapp:search' %}" role="search" method="get">
                            <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                          </form>
                        </div>
                    </nav>

                    {% if result %}
                        {% for res in result %}
                        <div class="col-md-9 mx-3 d-flex justify-content-center">
                            <div class="card my-4 shadow p-3 mb-5 bg-white rounded">
                                <div class="card-header bg-dark text-white fs-3 fw-bold">{{ res.title }}</div>
                                <div class='card-body'>
                                    
                                    <h5 class="card-title">{{ res.blogger }}</h5>
                                    <h5 class="card-title">{{ res.published_date }}</h5>
                                    <img src="{% if res.image %} {{ res.image.url }} {% endif %}" class="rounded" style ="max-height:100%; max-width:100%;">
                                    <p class="card-text" >
                                    {{ res.content|truncatechars:75 }}
                                    </p>
                                    
                                    <a href="{% url 'blogapp:detail' pk=res.id %}" class="btn btn-primary">Read More</a>
                                </div>
                                <div class="card-footer">Category :- {{ obj.category }}
                                    <br>
                                    {% for i in res.tags.all  %}
                                    Tags :- {{ i.name }}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>

                        {% endfor %}
                    
                    {% endif %}

                    {% if msg %}
                    {{ msg }}
                    {% endif %}

                    {% for obj in view.choices %}

                        <div class="col-md-9 mx-3 d-flex justify-content-center">
                            <div class="card my-4 shadow-lg p-3 mb-5 bg-white rounded">
                                <div class="card-header bg-dark text-white fs-3 fw-bold">{{ obj.title }}</div>
                                <div class='card-body'>
                                    
                                    <h5 class="card-title">{{ obj.blogger }}</h5>
                                    <h5 class="card-title">{{ obj.published_date }}</h5>
                                    <img src="{% if obj.image %} {{ obj.image.url }} {% endif %}" class="rounded" style ="max-height:100%; max-width:100%;">
                                    <p class="card-text" >
                                    {{ obj.content|truncatechars:75 }}
                                    </p>
                                    
                                    <a href="{% url 'blogapp:detail' pk=obj.id %}" class="btn btn-primary">Read More</a>
                                </div>
                                <div class="card-footer">Category:- {{ obj.category }}
                                    <br>
                                    {% for i in obj.tags.all  %}
                                    Tags :- {{ i.name }}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    
                
                    {% endfor %}
                </div>
            </div>
            
            <div class="bg-dark col-sm-3 d-flex align-items-center">
                <div class="row d-flex ">
                    
                        <img src="{% static 'images/picc.jpg' %}" class="rounded p-4 mt-4" alt="Cinque Terre" style="max-width:100%;max-height:100%; border-radius: .50rem;" >                         
                    
                </div>
            </div>
            
        </div>
    </div>
</section>


{% endblock %}