pep/blogapp/urls.py
from django.urls import path
from blogapp import views
from blogapp.views import Blogging, BlogCreate
from django.conf import settings
from django.conf.urls.static import static

app_name = "blogapp"

urlpatterns = [
    path('', views.Blogging.as_view(),name="index"),
    path('create/', views.BlogCreate.as_view(),name="create"),
    path('update/<int:pk>/',views.BlogUpdate.as_view(),name='update'),
    path('detail/<int:pk>/',views.BlogDetail.as_view(),name='detail'),
    path('delete/<int:pk>/',views.BlogDelete.as_view(),name='delete'),
    path('list/',views.BlogList.as_view(),name='list'),
    path('listHome/',views.BlogHome.as_view(),name='bloghome'),
    path('listRate/',views.BlogListRating.as_view(),name='blograte'),
    path('remove/<int:pk>/', views.remove, name='remove'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('results/', views.SearchView.as_view(), name='search'),
    path('like/<int:pk>/', views.postLike, name='like'),
    path('dislike/<int:pk>/', views.postDisLike, name='dislike'),
    path('list_user/',views.BlogListUser.as_view(),name='listuser'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pep/mypep/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as pep_views
from mypep.views import MyView, SignUpView, UserLogin, ProfileUpdate, ProfileDetail, MyDetailView


app_name = "mypep"

urlpatterns = [
    path('', MyView.as_view(), name="base"),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='mypep:login'), name='logout'),

    path('update/<int:pk>', ProfileUpdate.as_view(), name='update'),

    path('detail/', MyDetailView.as_view(), name='detail'),


    path('change/', pep_views.PasswordChangeView.as_view(template_name="mypep/password_change_form.html",
                                                          success_url=reverse_lazy('mypep:password_change_done')), name='password_change'),
    path('change_done/', pep_views.PasswordChangeDoneView.as_view(template_name="mypep/password_change_done.html",),
                                                                  name='password_change_done'),

    path('reset_password/', pep_views.PasswordResetView.as_view(template_name="mypep/password_reset_form.html",success_url=reverse_lazy('mypep:password_reset_done')), 
    name = 'password_reset'),
    path('reset_password_sent/', pep_views.PasswordResetDoneView.as_view(template_name="mypep/password_reset_done.html"), 
    name = 'password_reset_done'),
    path('reset/<uidb64>/<token>', pep_views.PasswordResetConfirmView.as_view(template_name="mypep/password_reset_confirm.html",success_url=reverse_lazy('mypep:password_reset_complete')), 
    name = 'password_reset_confirm'),
    path('reset_password_complete/', pep_views.PasswordResetCompleteView.as_view(template_name="mypep/password_reset_complete.html"), 
    name = 'password_reset_complete')
]

pep/pep/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.templatetags.static import static
from django.conf.urls.static import static

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path("admin/", admin.site.urls),
    path("mypep/", include('mypep.urls')),
    path("adminpanel/", include('adminpanel.urls')),
    path("blogapp/", include('blogapp.urls')),
    path("blogcomment/", include('blogcomment.urls')),
    path("product/",include('modules.product.ProductApp.urls', namespace='product'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pep/mypep/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver


class ProfileModel(models.Model):
    """
        User Profile Model for User details
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_image = models.ImageField(upload_to='images', default="",
                                   blank=True, null=True)
    user_gender = models.CharField(max_length=300, blank=True, null=True)
    user_location = models.TextField(max_length=300, blank=True, null=True)
    user_job_role = models.CharField(max_length=300, blank=True, null=True)
    user_bio = models.CharField(max_length=300, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True)

    # Slugify Function
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        return super().save(*args, **kwargs)


# Signal for user onetoone field
@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        ProfileModel.objects.create(user=instance)


class AuthModel(models.Model):
    """
    Auth Model 
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    forget_password_token = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

pep/mypep/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# Sign Up Form
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address')

    class Meta:
        model = User
        fields = [
            'username', 
            'first_name', 
            'last_name', 
            'email', 
            'password1', 
            'password2', 
            ]

# class ProfileForm()

pep/mypep/views.py
import os
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views import View
from django.urls import reverse_lazy
from mypep.forms import SignUpForm
from mypep.models import ProfileModel


class UserLogin(LoginView):
    """
    LoginView which by default provides us with a form
    """
    template_name = 'mypep/login.html'
    fields = "__all__"
    redirect_authenticated_user = True
    success_url = reverse_lazy('mypep:base')


class SignUpView(CreateView):
    """
    Created SignupView which has SignUpForm for user registraion
    """
    form_class = SignUpForm
    success_url = reverse_lazy('mypep:base')
    template_name = 'mypep/signup.html'

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(SignUpView, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('mypep:base')
        return super(SignUpView, self).get(*args, **kwargs)


class MyView(View):
    """
    Home page view
    """

    def get(self, request):
        """
        Function to render home page
        """
        return render(request, 'mypep/hello.html')


# class ProfileUpdate(UpdateView):
#     model = ProfileModel
#     template_name = 'mypep/profilemodel_update.html'
#     fields = '__all__'
#     pk_url_kwarg = 'pk'
#     success_url = reverse_lazy('mypep:detail')

#     def form_valid(self, form):
#         # Get the user's current profile picture
#         old_picture = self.request.user.user_image

#         # Delete the old profile picture
#         if old_picture:
#             os.remove(os.path.join(settings.MEDIA_ROOT, str(old_picture)))

#         # Update the user's profile picture
#         self.request.user.user_image = form.cleaned_data['user_image']
#         self.request.user.save()

#         return super().form_valid(form)



class ProfileUpdate(UpdateView):
    model = ProfileModel
    fields = '__all__'
    template_name = 'mypep/profilemodel_update.html'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('mypep:detail')

    def form_valid(self, form):
        print(self.request.user.profilemodel.user_location)
        print('3333333333333333333')
        
        # Get the user's current profile picture
        old_picture = self.request.user.profilemodel.user_image

        # Assign the new profile picture from the form
        self.request.user.user_image = form.cleaned_data['user_image']

        # Delete the old profile picture if it exists
        if old_picture:
            old_picture_path = os.path.join(settings.MEDIA_ROOT, str(old_picture))
            # if os.path.exists(old_picture_path):
            os.remove(old_picture_path)

        return super().form_valid(form)


class ProfileDetail(DetailView):
    model = 'ProfileModel'
    fields = '__all__'


class MyDetailView(View):
    """
    Home page view
    """

    def get(self, request):
        """
        Function to render home page
        """
        return render(request, 'mypep/profilemodel_detail.html')

pep/mypep/templates/mypep/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
        {% endblock %}</title>

        {% load static %}
        <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    {% block style %}
        {% endblock %}
  </head>
  <body>
    {% block content %}
        {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

pep/mypep/templates/mypep/hello.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% block content %}

<div class ="d-flex justify-content-center p-5">
    <div class="d-flex justify-content-center">
        <div class="card shadow text-center mt-5 bg-warning p-3" style="width: 300px;font-family: georgia;">
            <h1>Hello</h1><hr>

            {% if request.user.is_authenticated %}
            
            <p class="fw-bold fs-4">Logged in as - {{ request.user }}</p>

            <div class ="mb-4 fs-4">
                <a class="btn btn-primary" href = "{% url 'mypep:logout' %}">LOGOUT</a>
            </div>

            {% else %}

            <h2>Please Login To Continue</h2>

            <div class ="mb-4 fs-4">
                <a class="btn btn-primary" href = "{% url 'mypep:login' %}">Login</a>
            </div>

            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

pep/mypep/templates/mypep/login.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% block content %}

<section class="h-100">
    <div class = "container-fluid">
        <div class = "row" id="main">
            <div class="col-sm-6 text-black" id="coll">
                <div class="px-5 ms-xl-4 mt-5">
                    <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" ></i>
                    <span class="h1 fw-bold mb-0">Logo</span>
                </div>

                <div class="d-flex align-items-center h-custom-2 ps-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">


                    <div class="card-body fs-3" id="cardd" style="font-family:Times">
                        <form method="POST">
                            {% csrf_token %}
                            {{form.as_p}}
                            <input class="button" type="submit" value="Login">
                        </form>
                        <div class='mt-4'>
                            <a href = "{% url 'mypep:password_reset' %}">Forgot Password</a>
                            <p>Don't have an account? <a href="{% url 'mypep:signup' %}">Sign Up</a></p>
                            
                        </div>
                    </div>   
                </div>
            </div>


                <div class="col-sm-6  d-sm-block d-flex align-content-around" id='imge'>
                    <img src="{% static 'Images/login.jpg.svg' %}"
                      alt="Login image" class="w-100 vh-100" style="">
                </div>
                
        </div>
    </div>
</section>

    <style>
        input[type=submit]{
            background-color: #04AA6D;
            border-radius: 25px;
            color: white;
            padding: 16px 32px;
            text-decoration: none;
            margin: 4px 2px;
            cursor: pointer;
          }


          @media screen and (max-width:600px){

            #main{
                width:100%;
            }
            #main #cardd{
                width:100%;
                font-size:25px;
            }

            #main #coll{
                width:100%;
            }

            #main #cardd,#imge{
                width:100%;
            }

            #main #imge{
                height:auto;
            }

            #main #imge img{
                height:auto;
            }
          } 
    </style>

{% endblock %}

pep/mypep/templates/mypep/password_change_done.html
{% extends 'mypep/base.html' %}
{% load static %}
{% block content %}


    <div class="d-flex justify-content-center">
        <div class="card text-center mt-5" style="width: 300px;">
            <div class="card-header h5 text-white bg-primary">Password Changed Successfully !!!</div>
        </div>
    </div>


<style>
    body{
        background-color : #36302f;
    }
</style>

{% endblock %}

pep/mypep/templates/mypep/password_change_form.html
{% extends 'mypep/base.html' %}
{% load static %}
{% block content %}

<div class="d-flex justify-content-center bg-dark">
    <div class="card text-center " style="width: 300px;">
        <div class="card-header h5 text-white bg-primary">Password Change</div>
        <div class="card-body px-5">

            <form method = "POST" enctype = "multipart/form-data">
                {% csrf_token%}
                <div class="form-group">
                    {{form.as_p}}
                </div>
                <input type = "submit" value ="Submit">
            </form>

        </div>
    </div>
</div>

<style>
    input[type=submit]{
        background-color: #04AA6D;
        border-radius: 25px;
        color: white;
        padding: 16px 32px;
        text-decoration: none;
        margin: 4px 2px;
        cursor: pointer;
      }
</style>

{% endblock %}

pep/mypep/templates/mypep/password_reset_complete.html
{% extends 'mypep/base.html' %}
{% load static %}
{% block content %}


    <div class="d-flex justify-content-center">
        <div class="card text-center mt-5" style="width: 300px;">
            <div class="card-header h5 text-white bg-success">Password <br>Reset Completed !!!</div>
        </div>
    </div>


<style>
    body{
        background-color : #36302f;
    }
</style>

{% endblock %}

pep/mypep/templates/mypep/password_reset_confirm.html
change the password
<form method = "POST" enctype = "multipart/form-data">
    {% csrf_token%}
    <div class="form-group">
    {{form.as_p}}
    </div>
    <input type = "submit" value ="Submit">
</form>

pep/mypep/templates/mypep/password_reset_done.html
{% extends 'mypep/base.html' %}
{% load static %}
{% block content %}


    <div class="d-flex justify-content-center">
        <div class="card text-center mt-5" style="width: 300px;">
            <div class="card-header h5 text-white bg-success">Mail Sent !!!</div>
        </div>
    </div>


<style>
    body{
        background-color : #36302f;
    }
</style>

{% endblock %}

pep/mypep/templates/mypep/password_reset_form.html
<form method = "POST" enctype = "multipart/form-data">
    {% csrf_token%}
    <div class="form-group">
        {{form.as_p}}
    </div>
    <input type = "submit" value ="Submit">
</form>

pep/mypep/templates/mypep/profilemodel_detail.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% block content %}

    <section class="h-100 gradient">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-lg-9 col-xl-7">
                    <div class="card">
                        <div class="rounded-top text-white d-flex flex-row" style="background-color: #000; height:200px;">
                            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                                {% load static %}
                                <img src="{{ request.user.profilemodel.user_image.url }}"
                                            alt="Generic placeholder image" class=" img-thumbnail mt-4 mb-2"
                                            style="width: 150px;height:150px; z-index: 1">
                                
                                    <button class="btn btn-outline-dark " onclick="location.href='{% url 'mypep:update' pk=user.id %}';" data-mdb-ripple-color="dark"
                                    style="z-index: 1;">
                                        Update Profile
                                    </button>
                                
                            </div>

                            <div class="ms-3" style="margin-top: 130px;">
                                <h5>{{ request.user.username }}</h5>
                                <p>Kolkata</p>
                            </div>
                        </div>
                        
                        <div class="card-body p-4 text-black">
                            <div class="my-5 mx-3">
                                <p class="lead fw-normal mb-1">About</p>
                                <a class='btn btn-outline-dark' href="{% url 'blogapp:listuser' %}">Blogs</a>
                                <div class="p-4" >
                                    <p class="font-italic mb-1">Junior Software Developer</p>
                                    <p class="font-italic mb-1">Lives in Kolkata</p>
                                    <p class="font-italic mb-0">Coder</p>
                                </div>
                            </div>

                            <div class="d-flex justify-content-between align-items-center mb-4">
                                <p class="lead fw-normal mb-0">Recent photos</p>
                            </div>

                            <div class="row g-2">
                                <div class="col mb-2">
                                    <img src="{% static 'Images/pic1.svg'%}"
                                      alt="image 1" class="w-100 rounded-3">
                                </div>

                                <div class="col mb-2">
                                    <img src="{% static 'Images/pic4.svg'%}"
                                      alt="image 1" class="w-100 rounded-3">
                                </div>


                                <div class="col mb-2">
                                    <img src="{% static 'Images/pic3.svg'%}"
                                      alt="image 1" class="w-100 rounded-3">
                                </div>
                            </div>
                        
                        </div>
                    <div>
                </div>
            </div>
        </div>
    </section>

    {% load static %}
<!-- Footer -->


{% endblock %}

pep/mypep/templates/mypep/profilemodel_form.html
hey

pep/mypep/templates/mypep/profilemodel_update.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% block content %}


<div class="d-flex justify-content-center bg-dark">
    <div class="card shadow ">
        <div class="card-header bg-dark text-white d-flex justify-content-center">
            <p class="fw-bold fs-4">Update Profile</p>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save">
            </form>
        </div>
    </div>
</div>


<style>
    input[type=submit]{
        background-color: #04AA6D;
        border-radius: 25px;
        color: white;
        padding: 16px 32px;
        text-decoration: none;
        margin: 4px 2px;
        cursor: pointer;
      }
</style>

{% endblock %}



{% comment %} 
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form> {% endcomment %}

pep/mypep/templates/mypep/signup.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% block content %}
{% load widget_tweaks %}

    <section class="h-100 bg-dark">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col">
                    <div class="card card-registration my-4">
                        <div class="row g-0">
                            <div class="col-xl-6 d-none d-xl-block mt-5">
                                <img src="{% static 'Images/signup2.svg' %}"
                                  alt="Sample photo" class="img-fluid"
                                  style="border-top-left-radius: .25rem; border-bottom-left-radius: .25rem;" />
                              </div>

                              <div class="col-xl-6">
                                    <div class="card-body p-md-5 text-black">

                                        <h3 class="mb-5 text-uppercase">Sign Up Form</h3>

                                        <div class="row">
                                            <div class="col-md-6 mb-4">
                                                <div class="form-outline mb-4">
                                                    <form method = "POST">
                                                
                                                        {% csrf_token %}
                                                        {% comment %} {{ form.as_p }} {% endcomment %}
                                                        {% render_field form.username type="text" class="form-control" id="exampleInputUsername" placeholder="Username" %}<br>
                                                        {% render_field form.first_name class="form-control" placeholder="First Name" type="text" %}<br>                                                                                                       
                                                        {% render_field form.email type="email" class="form-control" id="exampleInputEmail" placeholder="Email" %}<br>
                                                        {% render_field form.password1 type="password" class="form-control" id="exampleInputPassword" placeholder="Password" %}
                                                        <p class='fs-8'>Password must contain at least 8 characters</p>
                                                        {% render_field form.password2 type="password" class="form-control" id="exampleInputPassword1" placeholder="Confirm Password" %}
                                                        <p class='fs-8'>Enter same password as above</p>
                                                        <button type="submit" class="btn btn-warning btn-lg ms-2">Submit</button>

                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                              </div>
                        </div>
                    </div>
                </div>
            </div>          
        </div>
    </section>


{% endblock %}